version: '3.8'
services:
  web1:
    build: .
    volumes:
      - ./app:/app
    environment:
      SERVER_ID: SERVER-1
    depends_on:
      - migration
      - redis
      - postgres

  web2:
    build: .
    volumes:
      - ./app:/app
    environment:
      SERVER_ID: SERVER-2
    depends_on:
      - migration
      - redis
      - postgres

  migration:
    build: .
    command: alembic upgrade head
    volumes:
      - ./app:/app
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 1s
      retries: 10
      timeout: 10s

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./app:/app