name: Run tests workflow

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - run: python -m pip install -r requirements-dev.txt

      - run: python -m flake8 app/

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BRANCH_NAME
          script: |
            sudo rm -rf pyforge-python-school-3
            git clone -b $BRANCH_NAME https://github.com/natatapkina/pyforge-python-school-3.git
            cd pyforge-python-school-3
            docker compose up --build -d